Refactor/components
storyofams/next-boilerplate pull request #31
Opened 2020-09-22 07:54 UTC by aidana12

Mostly cosmetic and consistency changes
- Made storybook more organised/consistent/prettier
- Added link component
- Button can now also be a link
- Made a quick fix for the grid, but needs to be looked into further: https://github.com/storyofams/next-boilerplate/issues/30
- Inputs should be minimum of 16px on mobile or iphone will zoom into the input when you click on it

2020-09-22 10:13 UTC, MrBamBam commented
Is there a specific reason that you named all 'primary' stories `Default` ?

I think the convention for it is to use basic if no other applicable name can be used. Default is an odd one and might conflict with the actual 'reserved' keyword `default`.

It probably isn't complaining because it's used as the name of react. But I think as a general rule of thumb we should avoid usage of the word `default`.

2020-09-22 11:09 UTC, MrBamBam requested changes
Do not prefix interfaces with `I` but suffix them with `Props`

2020-09-22 21:55 UTC, aidana12 commented on src/components/common/Box/Box.tsx
> -const Box = styled.div<System>`
I renamed all interfaces to somethingProps, including the system :) Hope this resolves the conversation.

2020-09-25 06:59 UTC, MrBamBam approved these changes

2020-09-25 06:59 UTC, merged