chore: default page styling + error page refactor
storyofams/next-boilerplate pull request #61
Opened 2021-01-25 08:53 UTC by leeuwis

2021-01-27 08:25 UTC, aidana12 requested changes

2021-01-27 08:25 UTC, aidana12 commented on src/pages/index.tsx
> +const cover = { top: 0, bottom: 0, left: 0, right: 0 };
Not sure if this should be separated, I don't see the value in that

2021-01-29 16:33 UTC, leeuwis commented on src/pages/_error.tsx
>  const getError = ({ res, err }) => {
I think the current implementation is the right balance between compact and readable (same how Next does it in their docs)

2021-01-29 16:34 UTC, leeuwis commented on src/pages/index.tsx
> +      {[...Array(5000)].map((_, i) => (
Was meant to be animated, but the my laptop almost exploded when I tried to animate them 😄 
Feel free to optimize it with an SVG pattern.

2021-02-09 11:57 UTC, leeuwis commented
Needs to be reviewed again after the `react-ui` theme update

2021-02-27 18:48 UTC, merged